name: Build Nightly
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build-nightly:
    name: Build Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
