name: Release
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ !contains(github.ref, 'main') && !contains(github.ref, 'master') }}
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main
      - uses: actions/checkout@v4
      - name: Cargo check
        run: cargo check --workspace
      - name: Cargo publish verify
        run: cargo publish --dry-run
      - uses: google-github-actions/release-please-action@v4
        id: release
      - name: After released
        run: |
          echo "release_created:${{ steps.release.outputs.release_created }}"
          echo "tag_name:${{ steps.release.outputs.tag_name }}"
          echo "major:${{ steps.release.outputs.major }}"
          echo "minor:${{ steps.release.outputs.minor }}"
          echo "patch:${{ steps.release.outputs.patch }}"
      - name: Cargo publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
  build:
    name: ${{ matrix.target }}
    needs:
      - release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
        

