name: Build by upload-rust-binary-action
permissions:
  contents: write
on:
  push:
    tags:
      - "*"
env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
defaults:
  run:
    shell: bash
jobs:
  upload-assets:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
            leading_dir: true
          - target: aarch64-unknown-linux-musl
            os: ubuntu-22.04
            bin_leading_dir: bin
          - target: aarch64-apple-darwin
            os: macos-12
            bin_leading_dir: opt/bin/leading
            leading_dir: true
          - target: aarch64-pc-windows-msvc
            os: windows-2022
            bin_leading_dir: opt/bin
            leading_dir: true
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            bin_leading_dir: opt
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
            leading_dir: false
          - target: x86_64-apple-darwin
            os: macos-12
            bin_leading_dir: leading-dir
          - target: x86_64-pc-windows-msvc
            os: windows-2022
          - target: x86_64-unknown-freebsd
            os: ubuntu-22.04
            leading_dir: true
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu')
      - uses: taiki-e/install-action@cross
        if: contains(matrix.target, '-musl')
      - run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> "${GITHUB_ENV}"
        if: endsWith(matrix.target, 'windows-msvc')
      - uses: linrongbin16/upload-rust-binary-action@feat-bin-dir
        with:
          archive: ${{ format('cargo-ci-template-{0}', matrix.target) }}
          bin: cargo-ci-template,hello,cargo-ci-template1,cargo-ci-template2,cargo-ci
          target: ${{ matrix.target }}
          tar: all
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
          include: "README.md,LICENSE"
          checksum: sha256
          leading-dir: ${{ matrix.leading_dir }}
          bin-leading-dir: ${{ matrix.bin_leading_dir }}
      - name: After Build
        run: |
          echo "ls -lah --color=always"
          ls -lah --color=always
